QA-214: Package 'latest' Mender client debian package by default
mendersoftware/mender-convert pull request #244
Opened 2020-10-23 06:57 UTC by oleorhagen

This cannot be merged until https://github.com/mendersoftware/mender-dist-packages/pull/34 is in, and a latest package is merged obviously.

2020-10-23 08:44 UTC, lluiscampos requested changes
I don't think this will work, as the pipeline will override with master (see [here](https://github.com/mendersoftware/mender-convert/blob/master/.gitlab-ci.yml#L8)).

But also, I am not sure that we want this to be mender latest [tag] instead of master for mender-convert/master. We need to discuss this once more.

2020-10-23 09:39 UTC, lluiscampos commented
> I don't think this will work, as the pipeline will override with master (see [here](https://github.com/mendersoftware/mender-convert/blob/master/.gitlab-ci.yml#L8)).
> 
> But also, I am not sure that we want this to be mender latest [tag] instead of master for mender-convert/master. We need to discuss this once more.

As discussed in the call, this is correct but we also have to change the pipeline to use `latest`.

2020-11-04 09:07 UTC, lluiscampos approved these changes

2020-11-04 09:26 UTC, oleorhagen commented
2.2.x-cherry: https://github.com/mendersoftware/mender-convert/pull/253

2020-11-04 09:37 UTC, merged