configs/images/raspberrypi_raspbian_config: Allow APT Suite change
mendersoftware/mender-convert pull request #380
Opened 2021-09-13 13:55 UTC by lluiscampos

As per today, our pre-converted image ships with Debian buster, while
Raspberry Pi OS APT repository has moved already to Debian bullseye,
moving buster from "stable" to "oldstable".

This configuration allows apt to update the information without
interaction from the user. This is the default behaviour in newer
versions of apt, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931566

2021-09-13 14:07 UTC, 0lmi approved these changes
LGTM. The only thing to consider additionally is [docs](https://docs.mender.io/get-started/preparation/prepare-a-raspberry-pi-device#step-1-flash-the-raspberry-pi) update with this info.

2021-09-13 14:09 UTC, lluiscampos commented
> LGTM. The only thing to consider additionally is [docs](https://docs.mender.io/get-started/preparation/prepare-a-raspberry-pi-device#step-1-flash-the-raspberry-pi) update with this info.

This is not the only change we do, see the [main config file](https://github.com/mendersoftware/mender-convert/blob/master/configs/raspberrypi_config) for example. I think that for really interested people they would go to the Release notes, right? That will be recorded as we have a Changelog tag in the commit.

2021-09-13 15:37 UTC, 0lmi requested changes

2021-09-13 15:37 UTC, 0lmi commented on configs/images/raspberrypi_raspbian_config
> +    run_and_log_cmd "echo 'Acquire::AllowReleaseInfoChange::Suite \"true\"' \
```suggestion
    run_and_log_cmd "echo 'Acquire::AllowReleaseInfoChange::Suite \"true\";' \
```

2021-09-13 15:41 UTC, lluiscampos commented on configs/images/raspberrypi_raspbian_config
> +    run_and_log_cmd "echo 'Acquire::AllowReleaseInfoChange::Suite \"true\"' \
Thanks. fixed

2021-09-14 05:02 UTC, 0lmi approved these changes

2021-09-14 06:49 UTC, oleorhagen approved these changes

2021-09-14 06:58 UTC, merged